# 文件路径: inventory.ini

[kvm_nodes]
; 192.168.1.10
; 192.168.1.11

[lxc_nodes]
172.245.220.230 ansible_port=57137 deployment_env=real

# 定义一个包含上面所有机器的父组
[all_nodes:children]
kvm_nodes
lxc_nodes

# 定义全局 SSH 变量（假设你的机器都是 root 登录，并且已经配好了 SSH 密钥）
[all_nodes:vars]
ansible_user=root
ansible_python_interpreter=auto_silent
ansible_ssh_private_key_file=~/.ssh/id_ed25519_github